[project]
name = "VS_PYTHON"
version = "1.2.3"
# ...
requires-python = "==3.13" # This defines the compatible Python versions
dependencies = [
    "ipympl>=0.9.8",
    "jupyter>=1.1.1",
    "keras>=3.12.0",
    "matplotlib>=3.10.3",
    "nbconvert>=7.16.6",
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "pandoc>=2.4",
    "plotly>=6.3.0",
    "scikit-image>=0.25.2",
    "tdqm>=0.0.1",
    "tensorflow>=2.20.0",
]
